const challengeInstanceActionTypes = {
  STORE_CHALLENGE_INSTANCE_START: "STORE_CHALLENGE_INSTANCE_START",
  STORE_CHALLENGE_INSTANCE_SUCCESS: "STORE_CHALLENGE_INSTANCE_SUCCESS",
  STORE_CHALLENGE_INSTANCE_FAILURE: "STORE_CHALLENGE_INSTANCE_FAILURE",
  REMOVE_CHALLENGE_START: "REMOVE_CHALLENGE_START",
  REMOVE_CHALLENGE_SUCCESS: "REMOVE_CHALLENGE_SUCCESS",
  REMOVE_CHALLENGE_FAILURE: "REMOVE_CHALLENGE_FAILURE",
  FETCH_CHALLENGES_INSTANCES_START: "FETCH_CHALLENGES_INSTANCES_START",
  FETCH_CHALLENGES_INSTANCES_SUCCESS: "FETCH_CHALLENGES_INSTANCES_SUCCESS",
  FETCH_CHALLENGES_INSTANCES_FAILURE: "FETCH_CHALLENGES_INSTANCES_FAILURE",
  INCREASE_LIKES_CHALLENGE_INSTANCE_START:
    "INCREASE_LIKES_CHALLENGE_INSTANCE_START",
  INCREASE_LIKES_CHALLENGE_INSTANCE_SUCCESS:
    "INCREASE_LIKES_CHALLENGE_INSTANCE_SUCCESS",
  INCREASE_LIKES_CHALLENGE_INSTANCE_FAILURE:
    "INCREASE_LIKES_CHALLENGE_INSTANCE_FAILURE",
  INCREASE_UNLIKES_CHALLENGE_INSTANCE_START:
    "INCREASE_UNLIKES_CHALLENGE_INSTANCE_START",
  INCREASE_UNLIKES_CHALLENGE_INSTANCE_SUCCESS:
    "INCREASE_UNLIKES_CHALLENGE_INSTANCE_SUCCESS",
  INCREASE_UNLIKES_CHALLENGE_INSTANCE_FAILURE:
    "INCREASE_UNLIKES_CHALLENGE_INSTANCE_FAILURE"
};

export default challengeInstanceActionTypes;
