const challengeInstanceActionTypes = {
  ACCEPT_CHALLENGE: "ACCEPT_CHALLENGE",
  CANCEL_CHALLENGE: "CANCEL_CHALLENGE",
  STORE_CHALLENGE_INSTANCE_START: "STORE_CHALLENGE_INSTANCE_START",
  STORE_CHALLENGE_INSTANCE_SUCCESS: "STORE_CHALLENGE_INSTANCE_SUCCESS",
  STORE_CHALLENGE_INSTANCE_FAILURE: "STORE_CHALLENGE_INSTANCE_FAILURE",
  REMOVE_CHALLENGE_START: "REMOVE_CHALLENGE_START",
  REMOVE_CHALLENGE_SUCCESS: "REMOVE_CHALLENGE_SUCCESS",
  REMOVE_CHALLENGE_FAILURE: "REMOVE_CHALLENGE_FAILURE",
  FETCH_CHALLENGES_INSTANCE_START: "FETCH_CHALLENGES_INSTANCE_START",
  FETCH_CHALLENGES_INSTANCE_SUCCESS: "FETCH_CHALLENGES_INSTANCE_SUCCESS",
  FETCH_CHALLENGES_INSTANCE_FAILURE: "FETCH_CHALLENGES_INSTANCE_FAILURE"
};

export default challengeInstanceActionTypes;
