const challengeTemplateActionTypes = {
  PROPOSE_CHALLENGE_START: "PROPOSE_CHALLENGE_START",
  PROPOSE_CHALLENGE_FAILURE: "PROPOSE_CHALLENGE_FAILURE",
  STORE_CHALLENGE_TEMPLATE_START: "STORE_CHALLENGE_TEMPLATE_START",
  STORE_CHALLENGE_TEMPLATE_SUCCESS: "STORE_CHALLENGE_TEMPLATE_SUCCESS",
  STORE_CHALLENGE_TEMPLATE_AILURE: "STORE_CHALLENGE_TEMPLATE_FAILURE",
  FETCH_CHALLENGES_TEMPLATE_START: "FETCH_CHALLENGES_TEMPLATE_START",
  FETCH_CHALLENGES_TEMPLATE_SUCCESS: "FETCH_CHALLENGES_TEMPLATE_SUCCESS",
  FETCH_CHALLENGES_TEMPLATE_FAILURE: "FETCH_CHALLENGES_TEMPLATE_FAILURE",
  SET_CATEGORY_OVERVIEW: "SET_CATEGORY_OVERVIEW",
  INCREASE_LIKES_CHALLENGE_TEMPLATE_START:
    "INCREASE_LIKES_CHALLENGE_TEMPLATE_START",
  INCREASE_LIKES_CHALLENGE_TEMPLATE_SUCCESS:
    "INCREASE_LIKES_CHALLENGE_TEMPLATE_SUCCESS",
  INCREASE_LIKES_CHALLENGE_TEMPLATE_FAILURE:
    "INCREASE_LIKES_CHALLENGE_TEMPLATE_FAILURE",
  INCREASE_UNLIKES_CHALLENGE_TEMPLATE_START:
    "INCREASE_UNLIKES_CHALLENGE_TEMPLATE_START",
  INCREASE_UNLIKES_CHALLENGE_TEMPLATE_SUCCESS:
    "INCREASE_UNLIKES_CHALLENGE_TEMPLATE_SUCCESS",
  INCREASE_UNLIKES_CHALLENGE_TEMPLATE_FAILURE:
    "INCREASE_UNLIKES_CHALLENGE_TEMPLATE_FAILURE"
};

export default challengeTemplateActionTypes;
