const challengeTemplateActionTypes = {
  PROPOSE_CHALLENGE_START: "PROPOSE_CHALLENGE_START",
  PROPOSE_CHALLENGE_FAILURE: "PROPOSE_CHALLENGE_FAILURE",
  STORE_CHALLENGE_TEMPLATE_START: "STORE_CHALLENGE_TEMPLATE_START",
  STORE_CHALLENGE_TEMPLATE_SUCCESS: "STORE_CHALLENGE_TEMPLATE_SUCCESS",
  STORE_CHALLENGE_TEMPLATE_AILURE: "STORE_CHALLENGE_TEMPLATE_FAILURE",
  FETCH_CHALLENGES_TEMPLATE_START: "FETCH_CHALLENGES_TEMPLATE_START",
  FETCH_CHALLENGES_TEMPLATE_SUCCESS: "FETCH_CHALLENGES_TEMPLATE_SUCCESS",
  FETCH_CHALLENGES_TEMPLATE_FAILURE: "FETCH_CHALLENGES_TEMPLATE_FAILURE",
  SET_CATEGORY_OVERVIEW: "SET_CATEGORY_OVERVIEW"
};

export default challengeTemplateActionTypes;
