const usersActionTypes = {
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  ADD_FRIEND_START: "ADD_FRIEND_START",
  ADD_FRIEND_SUCCESS: "ADD_FRIEND_SUCCESS",
  ADD_FRIEND_FAILURE: "ADD_FRIEND_FAILURE",
  ACCEPT_FRIEND_START: "ACCEPT_FRIEND_START",
  ACCEPT_FRIEND_SUCCESS: "ACCEPT_FRIEND_SUCCESS",
  ACCEPT_FRIEND_FAILURE: "ACCEPT_FRIEND_FAILURE",
  DENY_FRIEND_START: "DENY_FRIEND_START",
  DENY_FRIEND_SUCCESS: "DENY_FRIEND_SUCCESS",
  DENY_FRIEND_FAILURE: "DENY_FRIEND_FAILURE",
  DELETE_FRIEND_START: "DELETE_FRIEND_START",
  DELETE_FRIEND_SUCCESS: "DELETE_FRIEND_SUCCESS",
  DELETE_FRIEND_FAILURE: "DELETE_FRIEND_FAILURE"
};

export default usersActionTypes;
